# [Info]
site_name: "YR-技术博客"
site_url: ""
site_author: yuerrd
site_description: 笔记
theme:
  name: material
  language: zh
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: orange  # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: indigo
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
markdown_extensions:
  - pymdownx.arithmatex: # latex支持
      generic: true
  - attr_list # 给图片后面添加{width="300"}设置大小
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
    # linenums: true # 显示行号
    # auto_title: true # 显示编程语言名称
  - pymdownx.superfences # 代码块高亮插件
  - meta # 支持Markdown文件上方自定义标题标签等
  - admonition # https://squidfunk.github.io/mkdocs-material/reference/admonitions/#inline-blocks
  - pymdownx.details # admonition需要
extra_javascript:
  # latex支持
  # check https://squidfunk.github.io/mkdocs-material/reference/mathjax/?h=math for more information
  # notice `curl https://polyfill.io/v3/polyfill.min.js?features=es6 > docs/mkdocs/javascripts/polyfill.min.js && curl https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js > docs/mkdocs/javascripts/tex-mml-chtml.js` not works... because there are other resources that need to load
  - mkdocs/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js # https://cdn.bytedance.com/?query=mathjax&version=3.2.0
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
  - mkdocs/css/unordered-list-symbols.css # multiplt unordered list symbols
extra:
  generator: false
  analytics:
    provider: google
    property: G-3R168EQ61K
  social:
    - type: 'github'
      link: 'https://github.com/yuerrd'

nav:
  - 一.算法:
      - 1.1RSA加密: algorithm/rsa.md
      - 1.2道格拉斯: algorithm/douglas-peucker.md
      - 1.3HyperLogLog: algorithm/hyper-log-log.md
  - 二.计算器学习:
      - 2.1基础数学: ai/basic-math.md
      - 2.2Python基础: ai/python-base.md
      - 2.3科学技术库: ai/computing-library.md
  - 三.Java:
      - 3.1基础: java/java.md
      - 3.2JVM: java/jvm.md
      - 3.3Synchronized: java/synchronized.md
      - 3.4ThreadLocal: java/thread-local.md
  - 四.常用命令:
      - 4.1Git: command/git.md
      - 4.2Hbase: command/hbase.md
      - 4.3Linux: command/linux.md
      - 4.4Supervisor: command/supervisor.md
  - 五.容器技术:
      - 5.1K8S安装: container/k8s.md
      - 5.2NFS安装: container/nfs.md
      - 5.3Prometheus安装: container/prometheus-outside-k8s-cluster.md
      - 5.4Mongodb安装: container/deploy-a-replica-set-mongodb.md
  - 六.常用组件:
      - 6.1Redis: component/redis.md
      - 6.2Zookeeper: component/zookeeper.md
      - 6.3Mysql: component/mysql.md
  - 七.其他:
      - 7.1自签名证书: other/cert-generation.md
      - 7.2网络: other/internet.md
      - 7.3IPv4: other/ipv4.md
      - 7.4常用应用安装: other/install.md
